'use client'

import Link from 'next/link'
import { ArrowRight, CheckCircle2, ChevronRight, Leaf, MapPin, Menu, Sparkles, Users, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Navbar, Footer } from '@/components/site-chrome'

const hackathons = [
  { title: 'Green Cities Hackathon 2026', tag: 'Climate & sustainability', date: 'Apr 18–20, 2026', place: 'Online + 12 cities', image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80', color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300' },
  { title: 'Rural Innovation Challenge', tag: 'Community development', date: 'May 09–11, 2026', place: 'Bengaluru + online', image: 'https://images.unsplash.com/photo-1509099836639-18ba02c6f7b4?auto=format&fit=crop&w=900&q=80', color: 'bg-sky-100 text-sky-800 dark:bg-sky-950 dark:text-sky-300' },
  { title: 'Health for All Hackathon', tag: 'Health & wellbeing', date: 'Jun 06–07, 2026', place: 'Online', image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80', color: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300' },
]

const problems = [
  { title: 'Waste Segregation in Colleges', category: 'Environment', place: 'Pune, India', votes: 124, avatar: 'PS' },
  { title: 'Lack of Digital Education Access', category: 'Education', place: 'Nairobi, Kenya', votes: 98, avatar: 'AM' },
  { title: 'Water Shortage in Urban Areas', category: 'Infrastructure', place: 'Cape Town, South Africa', votes: 87, avatar: 'NK' },
]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="min-h-screen bg-background text-foreground"><Navbar />
    <main>
      <section className="relative overflow-hidden border-b border-border bg-muted/35"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-24"><div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1.5 text-sm font-medium text-primary"><Sparkles className="size-4" /> A community-powered movement</div><h1 className="text-pretty text-5xl font-semibold leading-[1.05] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Turn community problems into <span className="text-primary">real-world solutions.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">Hack4Good brings communities and innovators together to solve the challenges that matter most—from the first idea to measurable impact.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link href="/hackathons">Explore hackathons <ArrowRight data-icon="inline-end" /></Link></Button><Button size="lg" variant="outline" asChild><Link href="/problems">Submit a problem</Link></Button></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-primary" /> Open to everyone</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-primary" /> Built for impact</span></div></div><div className="relative"><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-xl"><img src="https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=85" alt="A diverse team collaborating around a table" className="aspect-[1.1] w-full object-cover" /><div className="flex items-center justify-between border-t bg-card p-5"><div><p className="text-sm font-semibold">Your next big idea starts here.</p><p className="mt-1 text-sm text-muted-foreground">Join 12,400+ changemakers</p></div><div className="flex -space-x-2" aria-label="Community members"><span className="flex size-8 items-center justify-center rounded-full border-2 border-card bg-sky-200 text-xs font-semibold text-sky-900">JR</span><span className="flex size-8 items-center justify-center rounded-full border-2 border-card bg-amber-200 text-xs font-semibold text-amber-900">AM</span><span className="flex size-8 items-center justify-center rounded-full border-2 border-card bg-emerald-200 text-xs font-semibold text-emerald-900">+2k</span></div></div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">How it works</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Small steps. Shared momentum.</h2><p className="mt-4 text-lg leading-8 text-muted-foreground">From a challenge spotted in your neighborhood to a solution that scales, every contribution moves the work forward.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['01','Bring a problem','Share a challenge your community is facing and help it get the attention it deserves.'],['02','Build together','Find people with complementary skills and turn a shared purpose into a project.'],['03','Make an impact','Launch, learn, and track the change your team creates in the real world.']].map(([number,title,body]) => <div key={number} className="border-l-2 border-primary/25 pl-5"><p className="font-mono text-sm text-primary">{number}</p><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{body}</p></div>)}</div></section>
      <section className="border-y border-border bg-muted/30"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Find your challenge</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Featured hackathons</h2></div><Button variant="ghost" asChild><Link href="/hackathons">View all hackathons <ChevronRight data-icon="inline-end" /></Link></Button></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{hackathons.map((hackathon) => <article key={hackathon.title} className="overflow-hidden rounded-xl border border-border bg-card transition-shadow hover:shadow-lg"><img src={hackathon.image} alt="" className="aspect-[16/9] w-full object-cover" /><div className="flex flex-col gap-4 p-5"><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${hackathon.color}`}>{hackathon.tag}</span><h3 className="text-lg font-semibold leading-snug">{hackathon.title}</h3><div className="flex flex-col gap-2 text-sm text-muted-foreground"><span>{hackathon.date}</span><span className="flex items-center gap-1.5"><MapPin className="size-4" />{hackathon.place}</span></div><Button variant="outline" className="mt-1" asChild><Link href="/hackathons">View details <ArrowRight data-icon="inline-end" /></Link></Button></div></article>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Community voice</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Problems worth solving</h2></div><Button variant="outline" asChild><Link href="/problems">Explore all problems <ArrowRight data-icon="inline-end" /></Link></Button></div><div className="mt-10 grid gap-4">{problems.map((problem) => <article key={problem.title} className="flex flex-col gap-5 rounded-xl border border-border bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-primary/10 font-semibold text-primary">{problem.avatar}</span><div><h3 className="font-semibold">{problem.title}</h3><p className="mt-1 text-sm text-muted-foreground">{problem.category} · {problem.place}</p></div></div><div className="flex items-center justify-between gap-5 sm:justify-end"><span className="flex items-center gap-2 text-sm text-muted-foreground"><Users className="size-4" /> {problem.votes} supporters</span><Button variant="ghost" size="sm" asChild><Link href="/problems">View problem <ChevronRight data-icon="inline-end" /></Link></Button></div></article>)}</div></section>
      <section className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-16 lg:flex-row lg:items-center lg:justify-between lg:px-8 lg:py-20"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary-foreground/70">The impact is already growing</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Better ideas happen when more people get a seat at the table.</h2></div><div className="grid grid-cols-3 gap-7 sm:gap-12"><div><p className="text-3xl font-semibold">240+</p><p className="mt-1 text-sm text-primary-foreground/70">projects launched</p></div><div><p className="text-3xl font-semibold">48</p><p className="mt-1 text-sm text-primary-foreground/70">communities reached</p></div><div><p className="text-3xl font-semibold">12k</p><p className="mt-1 text-sm text-primary-foreground/70">changemakers</p></div></div></div></section>
      <section className="mx-auto max-w-3xl px-5 py-20 text-center lg:py-28"><Leaf className="mx-auto size-8 text-primary" /><blockquote className="mt-6 text-2xl font-medium leading-relaxed tracking-tight sm:text-3xl">“Hack4Good helped us turn a problem we had been talking about for years into a pilot our whole neighborhood could believe in.”</blockquote><p className="mt-5 text-sm text-muted-foreground">— Priya Shah, Green Warriors team lead</p></section>
    </main><Footer />
  </div>
}
